[package]
authors = ["Robert Lynch <robertlynch2012@gmail.com>"]
edition = "2018"
name = "save-parser"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1"
callback-future = "0.1"
console_error_panic_hook = "0.1.6"
enum_dispatch = "0.3.5"
fragile = "1.0.0"
hex = "0.4.3"
js-sys = "0.3"
serde = {version = "1.0", features = ["derive"]}
wasm-bindgen = {version = "0.2", features = ["serde-serialize"]}
wasm-bindgen-futures = "0.4.22"

[dependencies.web-sys]
features = [
  "File",
  "FileReader",
  "ProgressEvent",
  "EventTarget",
]
version = "0.3.49"
